Fix Octokit Client
Octokit client has a major breaking version that caused the Github
action workflow to fail with the following error:

```
/will-r-wang/game/octokit_client.rb:5:in `<class:OctokitClient>':
uninitialized constant Octokit::Preview (NameError)
Error: Process completed with exit code 1.
```

This updates the client syntax to hopefully get it to work again. 🤞